os-projects/clcrutch.json
Add PoSH Kentico to the OS list.
=> Add PoSH Kentico to the OS list.

os-projects/leeconlin.json
This adds a new entry to the list of open source packages for https://github.com/hades200082/Kentico12-MVC-WidgetResolver
=> Create leeconlin.json with first OS package

README.md
The linked website supports (and prefers) https protocol. No reason not to use it.
- N/A Automated tests have been added
- N/A Tests are passing
- N/A Docs have been updated (if applicable)
- N/A Temporary settings (e.g. variables used during development and testing) have been reverted to defaults
If manual testing is required, what are the steps? No testing.
=> Change http links to valid https links

marketplace/extensions.json
Redoing all pull requests, one at a time.  Starting with the bootstrap layout.
=> Adding bootstrap Extension

marketplace/extensions.json, scripts/checkExtensionsFormat.js
Internal link: https://kentico.atlassian.net/browse/DEVREL-256
Check changes in extension.json if they are OK.
=> Fix marketplace format

marketplace/extensions.json
I updated my repo so it should be up to date with yours, however be aware that the person waiting for their pull request will either need to do a re-pull once he fixes his icon, or you'll need to approve his, reject mine and i'll have to do the same.
=> Adding Page Builder Containers

marketplace/extensions.json
New color picker form component.
Also, when can we see the partner points for the 6 submissions for Heartland Business Systems?
=> Adding Improved Color Picker form component

marketplace/extensions.json
Listing Kentico Rich Text Editor to the marketplace.
**NOTE: MERGE AFTER https://github.com/Kentico/ems-mvc-components/pull/25 IS MERGED TOO**
no testing
=> Add Kentico Rich Text Editor to the marketplace

marketplace/extensions.json
Wanted to create a font awesome icon selector, so we have one available ready for use in projects.  Also meant I could test using K12 SP1 modal API.
Test installing form component on a new project following the readme instructions.
=> added Font Awesome Form Component

marketplace/extensions.json
Synchronizes all published content and assets from a specific site in Kentico EMS to a specific project in Kentico Kontent using the Content Management API.
=> Kentico Kontent Publishing Module

marketplace/extensions.json
TinyPNG image optimization module
=> TinyPNG image optimization module

marketplace/extensions.json
Requesting add of CKEditor4 Widget / Inline Editor implementation to Kentico Marketplace on behalf of Seventyeight Digital Inc.
=> Requesting add of CKEditor4 Widget / Inline Editor

marketplace/extensions.json
Requesting add of Masonry Image Gallery Widget implementation to Kentico Marketplace on behalf of Seventyeight Digital Inc.
@giorgioLUK
=> Requesting add of Masonry Image Gallery Widget

marketplace/extensions.json
Requesting add of Plyr Media Player Widget implementation to Kentico Marketplace on behalf of Seventyeight Digital Inc.
@giorgioLUK
=> Requesting add of Plyr Media Player Widget

marketplace/extensions.json
Added google map widget and uploaded package in nuget.org.
Updated Editable Image github path.
=> added google map widget

marketplace/extensions.json
Added Repeater, Image and Video Carousel, Image Card Widgets.
Uploaded respective packages to Nuget.org.
=> added Repeater, Image and Video Carousel, Image Card widgets

marketplace/extensions.json
A proposed new extension for the marketplace from 3 Degrees North that includes a series of EMS Email Marketing Templates and Widgets
=> New extension

marketplace/extensions.json
Include new module GatherContent Integration
=> Include new module GatherContent Integration

marketplace/extensions.json
Added new web part i.e., COVID-19 Country wise data to display the following details for all contries in the world.
Total Cases
Total Deaths
Total Recovered
New Deaths
New Cases
Critical 
Total tests
=> Added new web part i.e., COVID-19 Country wise data

marketplace/extensions.json
Adds 3 sample email widgets used in Kentico blog articles: Header image widget, Image with a hyperlink, Responsive text.
=> Adds 3 email widgets from Kentico articles

marketplace/extensions.json
Add Kentico Form Component for Google Recaptcha V3
=> Google reCAPTCHA V3 Marketplace Component

marketplace/extensions.json
=> Added Dynamic Routing Wildcards

marketplace/extensions.json
Image focuspoint provides helper tool for Kentico CMS and handle image presentation, by ensuring the 'spare' parts of your image (negative space) are cropped out before the important parts.
=> Added Image Focuspoint form component

marketplace/extensions.json
Updated version and author name "Visual Antidote" now matches Partner name in Partner portal.
=> Changed author name

marketplace/extensions.json
Added new component to the DevNet marketplace: **Staging Configuration Module**
=> Added Staging Configuration Module to DevNet

marketplace/extensions.json
thumbnail url wasn't working for some reason, so updated it
=> previous thumbnailUrl incorrect

marketplace/extensions.json
Only took about 70 hours...but my tools are updated for KX 13 full and core.
=> Updated 7 modules for KX 13, both full and .net core

marketplace/extensions.json
New Recombee integration for the Xperience. The new one replaces the old integration which was previously available.
=> Update Recombee integration

marketplace/extensions.json
Updated Staging Configuration Module to support Kentico Xperience 13
=> Updated Staging Configuration Module to support for Kentico Xperience 13

marketplace/extensions.json
Updated the URL Redirection module for Kentico Xperience 13 for both MVC.Net and MVC.Net Core
=> Added URL Redirection Module for 13

marketplace/extensions.json
Submission of new Filter By Category Widget by BitsOrchestra (mariia.zhokh@bitsorchestra.com)
=> New Filter By Category Widget

marketplace/extensions.json
Add new marketplace entry for https://github.com/wiredviews/xperience-rss-feeds
n/a
=> Add Marketplace entry for Xperience Community: RSS Feeds

marketplace/extensions.json
Added "Environment Connection String Module" to Marketplace
=> Added "Environment Connection String Module" to Marketplace

marketplace/extensions.json
Add Page listing widget to Marketplace
=> Add Page listing widget to Marketplace

marketplace/extensions.json
=> XTM Connect for Kentico CMS Marketplace

marketplace/extensions.json
New marketplace contribution for <https://github.com/wiredviews/xperience-page-link-tag-helpers>
n/a
=> Update extension.json with Page Link Tag Helpers repo

marketplace/extensions.json
New open source projects for the marketplace.
n/a
=> Add WiredViews utilities and modules

marketplace/extensions.json
=> add Google Search Console and Dynamics 365

marketplace/extensions.json
Add SendGrid (delayed Refresh 6 release)
=> Add SendGrid

marketplace/extensions.json
=> Added the following widgets to marketplace -

marketplace/extensions.json
=> Update extensions.json with hCaptcha library

marketplace/extensions.json
Adds Google Data Studio integration for Xperience Refresh 7. Don't merge until R7 release!
=> add Google Data Studio

marketplace/extensions.json
Adds the missing Bynder intergration developed a while ago
=> Add Bynder

marketplace/extensions.json
Adds the Xperience by Kentico Algolia integration, to be released in November Refresh
=> Add XbK Algolia

marketplace/extensions.json
Added new component to marketplace, without altering line-endings. 😃
=> Added 'TreeNode Selector Form Control' to marketplace
